#!/bin/bash
# /etc/init.d/ecdaemon

### BEGIN INIT INFO
# Provides:          ecdaemon
# Short-Description: Start EveryCook daemon
# Required-Start:    $all
# Required-Stop:     $all
# Should-Start:
# Should-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO

server_ip=`/opt/EveryCook/getServerIp.sh`
#server_ip=`/opt/EveryCook/getServerIp.sh`
server_ip=127.0.0.1
daemonPath=/opt/EveryCook/daemon
IPcheckPath=/opt/EveryCook/checkIP.sh
#daemonCommand="${daemonPath}/ecdaemon --config ${daemonPath}/config --middleware-and-file --middleware-server ${server_ip} --sim --sim7seg"
daemonCommand="${daemonPath}/ecdaemon --config ${daemonPath}/config --middleware-and-file --middleware-server ${server_ip}"

# Some things that run always
# Carry out specific functions when asked to by the system
case "$1" in
  restart)
    #stop
    if [ -f ${daemonPath}/ecdaemon.pid ]; then
        ps -e|grep `cat ${daemonPath}/ecdaemon.pid` > /dev/null
        if [[ $? -eq 0 ]]; then
			echo "Stopping ecdaemon"
			kill -15 `cat ${daemonPath}/ecdaemon.pid`
			sleep 3
			ps -e|grep `cat ${daemonPath}/ecdaemon.pid` > /dev/null
			if [[ $? -eq 0 ]]; then
			    kill -9 `cat ${daemonPath}/ecdaemon.pid`
			fi
			#rm ${daemonPath}/ecdaemon.pid
        fi
    fi
    #start
    ps -e|grep `cat ${daemonPath}/ecdaemon.pid` > /dev/null
    if [[ $? -eq 0 ]]; then
        echo "ecdaemon still running, stop not successfull"
        exit 2
    fi
    echo "Starting ecdaemon"
    ${IPcheckPath}
    ${daemonCommand}  > ${daemonPath}/ecdaemon.log 2>&1 &
    echo -ne $! > ${daemonPath}/ecdaemon.pid
    ;;
  start)
    if [ -f ${daemonPath}/ecdaemon.pid ]; then
        ps -e|grep `cat ${daemonPath}/ecdaemon.pid` > /dev/null
        if [[ $? -eq 0 ]]; then
            echo "ecdaemon already started"
            exit 2
        fi
    fi
    echo "Starting ecdaemon"
    ${daemonCommand}  > ${daemonPath}/ecdaemon.log 2>&1 &
    echo -ne $! > ${daemonPath}/ecdaemon.pid
    ;;
  stop)
    if [ -f ${daemonPath}/ecdaemon.pid ]; then
        ps -e|grep `cat ${daemonPath}/ecdaemon.pid` > /dev/null
        if [[ $? -ne 0 ]]; then
            echo "ecdaemon already stoped"
            exit 2
        fi
        echo "Stopping ecdaemon"
        kill -15 `cat ${daemonPath}/ecdaemon.pid`
        sleep 3
        ps -e|grep `cat ${daemonPath}/ecdaemon.pid` > /dev/null
        if [[ $? -eq 0 ]]; then
            kill -9 `cat ${daemonPath}/ecdaemon.pid`
        fi
        #rm ${daemonPath}/ecdaemon.pid
    else
        echo "pid file not found..."
        exit 3
    fi
    ;;
  *)
    echo "Usage: /etc/init.d/ecdaemon {start|stop}"
    exit 1
    ;;
esac

exit 0
